site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
edit_uri: edit/main/docs/
nav:
    - Installation Guide: 
      - HTML: documentation/guides/installation_guide.md
      - PDF: documentation/guides/installation_guide.pdf
    - Demo Package Guide:
      - HTML: documentation/guides/demo_package_guide.md
      - PDF: documentation/guides/demo_package_guide.pdf
    - For Business Users: 
      - Reference Guide: 
        - HTML: documentation/guides/reference_guide.md
        - PDF: documentation/guides/reference_guide.pdf
      - WebStudio User Guide:
        - HTML: documentation/guides/webstudio_user_guide.md
        - PDF: documentation/guides/webstudio_user_guide.pdf     
    - For Developers:
      - Rule Services Usage and Customization Guide: 
        - HTML: documentation/guides/rule_services_usage_and_customization_guide.md
        - PDF: documentation/guides/rule_services_usage_and_customization_guide.pdf
      - Developer Guide:
        - HTML: documentation/guides/developer_guide.md
        - PDF: documentation/guides/developer_guide.pdf
      - Activiti Integration Guide: 
        - HTML: documentation/guides/activiti_integration_guide.md
        - PDF: documentation/guides/activiti_integration_guide.pdf
      - Maven Plugin Guide: documentation/guides/maven_plugin_guide.md
    - THE OPENL PROJECT:
      - About OpenL: about.md
  
theme: readthedocs

repo_url: https://github.com/EISTW/OpenLdocs/

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
