site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
edit_uri: edit/v5.25/docs/
nav:
    - Installation Guide: documentation/OpenL Tablets - Installation Guide.pdf
    - Demo Package Guide: documentation/OpenL Tablets - Demo Package Guide.pdf
    - For Business Users: 
      - Reference Guide: documentation/OpenL Tablets - Reference Guide.pdf
      - WebStudio User Guide: documentation/OpenL Tablets - WebStudio User Guide.pdf
    - For Developers:
      - Rule Services Usage and Customization Guide: documentation/OpenL Tablets - Rule Services Usage and Customization Guide.pdf
      - Developer Guide: documentation/OpenL Tablets - Developer Guide.pdf
      - Activiti Integration Guide: documentation/OpenL Tablets - Activiti Integration Guide.pdf
    - About OpenL: about.md
  
theme: 
    name: material
    navigation_depth: 8
    theme_dir: site/css/theme_override
    custom_dir: site/css/theme_override
    logo: assets/logo.png
    features:
    - content.action.edit
    - content.action.view

repo_url: https://github.com/EISTW/OpenLdocs/

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
