site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
edit_uri: edit/main/docs/
nav:
  - USER GUIDES: 
    - Installation/demo guides: 
      - Installation Guide: documentation/OpenL Tablets - Installation Guide.pdf
      - Demo Package Guide: documentation/OpenL Tablets - Demo Package Guide.pdf
    - For Business Users: 
      - Reference Guide: documentation/OpenL Tablets - Reference Guide.pdf
      - WebStudio User Guide: documentation/OpenL Tablets - WebStudio User Guide.pdf
    - For Developers:
      - Rule Services Usage and Customization Guide: documentation/OpenL Tablets - Rule Services Usage and Customization Guide.pdf
      - Developer Guide: documentation/OpenL Tablets - Developer Guide.pdf
      - Activiti Integration Guide: documentation/OpenL Tablets - Activiti Integration Guide.pdf
      - Maven Plugin Guide: https://openl-tablets.org/files/openl-tablets/5.25.0/OpenL%20Tablets%20-%20Maven%20Plugin%20Guide/
  - THE OPENL PROJECT:
    - About OpenL: about.md
  
theme: readthedocs

repo_url: https://github.com/EISTW/OpenLdocs/

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
